name: Pull Request

on: [pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

  build:
    needs: setup
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 16
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Configure Flutter for Android
        run: |
          flutter config --enable-android
          flutter doctor -v

      - name: Build APK
        run: flutter build apk


  analyze:
    needs: setup
    runs-on: ubuntu-latest
    name: Analyze

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Analyze
        run: flutter analyze

  test:
    needs: setup
    runs-on: ubuntu-latest
    name: Test

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Test
        run: flutter test --coverage

      - name: Remove generated file from coverage
        run: dart pub run remove_from_coverage -f coverage/lcov.info -r '\.g\.dart$'

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
